### ISSUE TITLE
Project doesn't build - can't find ptr::from_ref

### ISSUE THREAD

**Issue by binarymax** [antoniosarosi/rxh#1]
Hi!  I cloned the repo and ran `cargo build` and I get the following error:

```
error[E0425]: cannot find function `from_ref` in module `ptr`
   --> src/task/server.rs:246:37
    |
246 |             drop(Box::from_raw(ptr::from_ref(config).cast_mut()));
    |                                     ^^^^^^^^ not found in `ptr`
    |

```

I am using rustc/cargo version 1.60.0 (on Ubuntu 20.04)

Any advice?

**Comment by binarymax** [comment]
Did some digging and looks like I need a new version of Rust!  https://github.com/rust-lang/rust/issues/106116

**Comment by antoniosarosi** [comment]
Well, I used a nightly version for this project, you can use `rustup override set nightly` while located in the project directory and then try to build it again. If you want to use the stable version, you have to modify that line of code:

```rust
drop(Box::from_raw(config as *mut Server));
```

Not sure if that will compile, I can't test it right now. I'll check later to confirm.

**Comment by binarymax** [comment]
I just used nightly and got it to build.  Thanks for the quick response!
